[platformio]
default_envs = native

[env]
framework = arduino
lib_deps = .

[env:native]
platform = native
build_flags = -std=c++17 -DUNIT_TEST
test_framework = unity

[env:esp32]
platform = espressif32
board = esp32dev
build_flags = -DUNIT_TEST
test_framework = unity

[env:uno]
platform = atmelavr
board = uno
build_flags = -DUNIT_TEST
test_framework = unity

[env:due]
platform = atmelsam
board = due
build_flags = -DUNIT_TEST
test_framework = unity