[platformio]
default_envs = native
test_dir = test

[env]
build_flags = -DUNITY_INCLUDE_CONFIG_H

[env:native]
platform = native
test_framework = unity

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity

[env:uno]
platform = atmelavr
board = uno
framework = arduino
test_framework = unity